# Generated by Django 4.1.7 on 2023-04-12 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(null=True)),
                ('frete', models.FloatField(default=0.0, null=True)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=150)),
                ('preco', models.FloatField(default=0.0)),
                ('quantidade', models.IntegerField(default=1)),
                ('imagem_capa', models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/')),
                ('imagem_2', models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/')),
                ('imagem_3', models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/')),
                ('stripe_id', models.CharField(max_length=200, null=True)),
                ('fk_carrinho', models.ManyToManyField(editable=False, to='lojarelogiosapp.carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('total', models.FloatField(default=0.0)),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone_1', models.CharField(max_length=25)),
                ('telefone_2', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=150)),
                ('rua', models.CharField(max_length=150)),
                ('numero_rua', models.CharField(max_length=150)),
                ('complemento', models.CharField(max_length=150, null=True)),
                ('cep', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('aceito', 'aceito'), ('despachado', 'despachado')], default='pendente', max_length=25)),
                ('link_rastreamento', models.URLField(null=True)),
                ('fk_carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojarelogiosapp.carrinho')),
            ],
        ),
    ]
