# Generated by Django 4.1.7 on 2023-03-29 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(null=True)),
                ('frete', models.FloatField(default=0.0, null=True)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('preco', models.FloatField(default=0.0)),
                ('quantidade', models.IntegerField(default=1)),
                ('imagem_capa', models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/')),
                ('imagem_2', models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/')),
                ('imagem_3', models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/')),
                ('fk_carrinho', models.ManyToManyField(editable=False, null=True, to='lojarelogiosapp.carrinho')),
            ],
        ),
    ]
