# Generated by Django 4.1.7 on 2023-04-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_casa',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
