# Generated by Django 4.1.7 on 2023-04-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=25),
        ),
    ]
