# Generated by Django 4.1.7 on 2023-04-04 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone_1', models.IntegerField()),
                ('telefone_2', models.IntegerField(null=True)),
                ('endereco_entrega_1', models.CharField(max_length=150)),
                ('endereco_entrega_2', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('aceito', 'aceito'), ('despachado', 'despachado')], default='pendente', max_length=25)),
                ('link_rastreamento', models.CharField(max_length=999, null=True)),
                ('fk_carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojarelogiosapp.carrinho')),
            ],
        ),
    ]
