# Generated by Django 4.1.7 on 2023-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_2',
            field=models.FileField(null=True, upload_to='lojarelogiosapp/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_3',
            field=models.FileField(null=True, upload_to='lojarelogiosapp/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_capa',
            field=models.FileField(null=True, upload_to='lojarelogiosapp/static/uploads/'),
        ),
    ]
