# Generated by Django 4.1.7 on 2023-04-28 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password_token',
            options={'verbose_name': 'Token de senha', 'verbose_name_plural': 'Tokens de senha'},
        ),
        migrations.AddField(
            model_name='password_token',
            name='data_cr',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
