# Generated by Django 4.1.7 on 2023-03-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='produto',
            name='qntd_disponivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_2',
            field=models.FileField(null=True, upload_to='./uploads/lojarelogiosapp/images/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_3',
            field=models.FileField(null=True, upload_to='./uploads/lojarelogiosapp/images/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_capa',
            field=models.FileField(null=True, upload_to='./uploads/lojarelogiosapp/images/'),
        ),
    ]
