# Generated by Django 4.1.7 on 2023-04-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0002_alter_produto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
