# Generated by Django 4.1.7 on 2023-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0002_alter_produto_imagem_2_alter_produto_imagem_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='qntd_disponivel',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_2',
            field=models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_3',
            field=models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_capa',
            field=models.FileField(null=True, upload_to='lojarelogiosapp/static/lojarelogiosapp/uploads/'),
        ),
    ]
