# Generated by Django 4.1.7 on 2023-04-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0002_pedido_numero_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.CharField(max_length=900, primary_key=True, serialize=False),
        ),
    ]
