# Generated by Django 4.1.7 on 2023-04-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0003_pedido_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='stripe_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
