# Generated by Django 4.1.7 on 2023-03-25 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojarelogiosapp', '0003_remove_produto_qntd_disponivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(null=True)),
                ('frete', models.FloatField(default=0.0, null=True)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='fk_carrinho',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lojarelogiosapp.carrinho'),
        ),
    ]
