# Generated by Django 4.1.7 on 2023-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0004_carrinho_produto_fk_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fk_carrinho',
        ),
        migrations.AddField(
            model_name='produto',
            name='fk_carrinho',
            field=models.ManyToManyField(to='lojarelogiosapp.carrinho'),
        ),
    ]
