# Generated by Django 4.1.7 on 2023-03-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojarelogiosapp', '0005_remove_produto_fk_carrinho_produto_fk_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fk_carrinho',
            field=models.ManyToManyField(editable=False, null=True, to='lojarelogiosapp.carrinho'),
        ),
    ]
